version: "3"

services:
    web:
        build: .
        image: silesiacoin/nodejs-authen:latest
        volumes:
            - ./:/var/www/app
        networks:
            silesiacoin:
                aliases:
                  - authenticator.local

networks:
    silesiacoin:
        driver: bridge
