version: "3"

services:
    web:
        image: silesiacoin/nodejs:latest
        volumes:
            - ./:/var/www/app
        ports:
            - 127.0.66.2:80:80
            - 127.0.66.2:443:443
            - 127.0.66.2:8081:8081
            - 127.0.66.2:8546:8545
            - 127.0.66.2:30304:30303
        networks:
            silesiacoin:
                aliases:
                  - authenticator.localhost
networks:
    silesiacoin:
        driver: bridge
